# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Integration
on:
  pull_request:
    branches: [main]
    paths-ignore:
      - .gitignore
      - .github/**
      - "!.github/workflows/integration.yml"
      - .husky/**
      - .idea/**
      - .vscode/**
      - "**.md"
      - "**.rst"
  push:
    branches: [main]
    paths-ignore:
      - .gitignore
      - .github/**
      - "!.github/workflows/integration.yml"
      - .husky/**
      - .idea/**
      - .vscode/**
      - "**.md"
      - "**.rst"
  workflow_dispatch:
    inputs:
      jobs:
        description: Comma-separated list of names of jobs to trigger
        required: false
        default: build

env:
  ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
  ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
  AUTH_GITHUB_ID: ${{ secrets.AUTH_GITHUB_ID }}
  AUTH_GITHUB_SECRET: ${{ secrets.AUTH_GITHUB_SECRET }}
  AUTH_GOOGLE_ID: ${{ secrets.AUTH_GOOGLE_ID }}
  AUTH_GOOGLE_SECRET: ${{ secrets.AUTH_GOOGLE_SECRET }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MONGO_DB: ${{ secrets.MONGO_DB }}
  MONGO_HOST: mongo
  MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
  NEXT_PUBLIC_GTM_ID: ${{ secrets.NEXT_PUBLIC_GTM_ID }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  SERVER_HOST: ${{ secrets.SERVER_HOST }}
  SHA: ${{ github.sha }}
  SMTP_USER: ${{ secrets.SMTP_USER }}
  SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}

jobs:
  changed-files:
    name: Get changed files
    runs-on: ubuntu-latest
    outputs:
      added-files: ${{ steps.changed-files.outputs.added_files }}
      deleted-files: ${{ steps.changed-files.outputs.deleted_files }}
      modified-files: ${{ steps.changed-files.outputs.modified_files }}
      all-changed-files: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42.1.0

  generate-dotenv:
    name: Generate .env file
    needs: [changed-files]
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.generate-dotenv.outputs.cache-key }}
    steps:
      - name: Check out main branch
        uses: actions/checkout@v3
      - id: generate-dotenv
        name: Generate .env file
        uses: iacobfred/generate-dotenv@v0.3.5
        with:
          output-path: .env
          template-paths: |
            .config/_.env
            .config/_.env.production
          cache: true
          upload: true
          key: dotenv-${{ github.sha }}-${{ github.run_id }}
          allow-missing-vars: true
        env:
          ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
          AUTH_GITHUB_ID: ${{ secrets.AUTH_GITHUB_ID }}
          AUTH_GITHUB_SECRET: ${{ secrets.AUTH_GITHUB_SECRET }}
          AUTH_GOOGLE_ID: ${{ secrets.AUTH_GOOGLE_ID }}
          AUTH_GOOGLE_SECRET: ${{ secrets.AUTH_GOOGLE_SECRET }}
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          NEXT_PUBLIC_GTM_ID: ${{ secrets.NEXT_PUBLIC_GTM_ID }}
          PORT: ${{ vars.PORT }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

  test:
    name: Build and test
    needs: [changed-files, generate-dotenv]
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: pnpm/action-setup@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      # - name: Restore dotenv
      #   uses: actions/cache@v3
      #   with:
      #     path: .env
      #     key: ${{ needs.generate-dotenv.outputs.cache-key }}
      - id: generate-dotenv
        name: Generate .env file
        uses: iacobfred/generate-dotenv@v0.3.5
        with:
          output-path: .env
          template-paths: |
            .config/_.env
            .config/_.env.production
      - name: Build
        run: pnpm build
        env:
          SENTRY_DRY_RUN: "true"
      - name: Test
        run: pnpm test

  docker:
    name: Build and push image
    if: ${{ github.actor != 'dependabot[bot]' }}
    needs: [changed-files, generate-dotenv]
    runs-on: ubuntu-latest
    steps:
      - name: Check out main branch
        uses: actions/checkout@v3
      # - name: Restore dotenv
      #   uses: actions/cache@v3
      #   with:
      #     path: .env
      #     key: ${{ needs.generate-dotenv.outputs.cache-key }}
      - id: generate-dotenv
        name: Generate .env file
        uses: iacobfred/generate-dotenv@v0.3.5
        with:
          output-path: .env
          template-paths: |
            .config/_.env
            .config/_.env.production
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image with cache
        id: build_with_cache
        # https://github.com/docker/build-push-action
        uses: docker/build-push-action@v5
        with:
          build-args: |
            PORT=${{ vars.PORT }}
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=gha
          cache-to: type=gha,scope=jacobjove,mode=max
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/iacobfred/jacobjove:${{ github.sha }},ghcr.io/iacobfred/jacobjove:latest
      - name: Build image without cache
        if: ${{ failure() && steps.build_with_cache.outcome == 'failure' }}
        uses: docker/build-push-action@v5
        with:
          build-args: |
            PORT=${{ vars.PORT }}
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,scope=jacobjove,mode=max
          tags: ghcr.io/iacobfred/jacobjove:${{ github.sha }}
      - name: Run containers
        run: |
          docker compose pull;
          docker compose up -d --no-build --wait || {
            docker compose logs nextjs;
            docker compose ps;
            exit 1;
          }
